In [1]:
import numpy

In [2]:
num=numpy.array([10,2,3,4,5,7,9,15])
num

array([10,  2,  3,  4,  5,  7,  9, 15])

In [3]:
import numpy as np 
numbers=np.array([1,2,5,4,6,8])
numbers

array([1, 2, 5, 4, 6, 8])

In [4]:
#shape of array / dimension (rows & coloumns)
numbers.shape

(6,)

In [5]:
#size of array / number of elements 
numbers.size


6

In [6]:
#size of memory needed for every entry in the array
numbers.itemsize

4

In [7]:
#number of dimensions of the array 
numbers.ndim

1

### 2   dimensional data 


([[c1,c2],[c1,c2]])                     
                            #>> the[  ] represents the rows .

In [8]:
p=numpy.array([[1,2],[3,4]])
p

array([[1, 2],
       [3, 4]])

In [9]:
p.shape
#output (row,coloumns)

(2, 2)

In [10]:
# 3 row ,4 coloumn
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
x.shape

(3, 4)

In [12]:
x.ndim

2

In [13]:
x.size

12

In [14]:
#reshape the array 
# the number of element or factor must be same 
x.reshape(4,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
#callable minimum value in array 
x.min()

1

In [16]:
#callable maximum value in array 
x.max()

12

In [17]:
x.dtype
#int32 is default data type 

dtype('int32')

In [18]:
x.data
#result is hexa decimal memory address in the ram 

In [19]:
#change of datatype 
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype="float64")
x

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [20]:
x.dtype

dtype('float64')

In [21]:
x.itemsize

#int takes 4 byte and float takes 8bytes

8

In [22]:
#ARANGE function holds same feature as RANGE func
seq=np.arange(15)
seq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
#can beassigned to variable as an array 
q=seq.reshape(3,5)
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
q.ndim

2

In [25]:
q.itemsize

4

In [26]:
q.size 

15

In [27]:
q.shape 


(3, 5)

In [28]:
q.dtype

dtype('int32')

In [29]:
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
q.ravel()
#prints the whole array in one line 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
print(q.ravel())

#prints the whole array in one line 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [32]:
#creating only zeros 
# default type is float
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
#creating only ones 
# default type is float
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 3   dimensional data 


In [34]:
w=np.ones((2,3,4))
w

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [35]:
w.ndim

3

In [36]:
np.empty([2,2])

array([[2.075e-321, 2.031e-321],
       [2.648e-321, 2.031e-321]])

# Broadcasting in numpy 

In [37]:
fa=np.array([1,8,9,5])
fb=np.array([2,0,1,8])

fc=fa*fb
fc

array([ 2,  0,  9, 40])

In [38]:
fd=fa*2
fd

array([ 2, 16, 18, 10])

In [39]:
fe=fb+50
fe

array([52, 50, 51, 58])

In [40]:
a=np.array([10,20,30,40,50])
b=np.arange(1,6)
a+b

array([11, 22, 33, 44, 55])

In [41]:
b**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [42]:
# random number between 0 to 1 
xc=np.random.random((2,3))
xc

array([[0.33795012, 0.82078054, 0.37710859],
       [0.52416563, 0.1341363 , 0.15612035]])

In [43]:
xd=np.ones((2,3))
xd

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
xc+xd

array([[1.33795012, 1.82078054, 1.37710859],
       [1.52416563, 1.1341363 , 1.15612035]])