# Statistics 

Descriptive stats 

In [1]:
import numpy as np

In [2]:
data=np.array([1,2,5,7,8,9,5,4,6,10,18,7,5,3,5,6,7,9,4,4,4,5,8,7])

In [3]:
data.mean()

6.208333333333333

In [4]:
data2=np.array([10,2,5,10,65,45,84,35,3])

In [5]:
data2.mean()
# calling mean function from inbuilt statistics 

28.77777777777778

In [6]:
np.mean(data2)
# calling mean function from numpy and assigning data2 as input 

28.77777777777778

In [7]:
np.median(data2)

10.0

In [8]:
import pandas as pd


In [9]:
list1=[1,5,4,7,9,6,9,8,6,8]

In [10]:
df=pd.DataFrame(data=list1)
df

0
0  1
1  5
2  4
3  7
4  9
5  6
6  9
7  8
8  6
9  8

In [11]:
df.mean()

0    6.3
dtype: float64

In [12]:
df.median()

0    6.5
dtype: float64

In [13]:
df.mode()

0
0  6
1  8
2  9

In [14]:
x=np.array([[7,8],[5,6],[7,5]])
x[1].mean()


5.5

In [15]:
x.mean()

6.333333333333333

In [16]:
(7+8+5+6+7+5)/6

6.333333333333333

stats in 1 dimensional array 

In [17]:
#from numpy import array 
alex=np.array([91,4,5,58,65,2,3,5,6])
alex

array([91,  4,  5, 58, 65,  2,  3,  5,  6])

In [18]:
alex.mean()

26.555555555555557

In [19]:
#variance 
alex.var()

1070.9135802469136

In [20]:
np.var(alex)

1070.9135802469136

In [21]:
#standard deviation 
alex.std()

32.724815969641654

stats in 2 dimensional array 

In [22]:
alexa=np.array([[91,4,5,58,65,2,3,5,6],[1,5,7,8,9,6,4,5,8]])


In [23]:
np.mean(alexa,axis=0)

array([46. ,  4.5,  6. , 33. , 37. ,  4. ,  3.5,  5. ,  7. ])

In [24]:
alexaN=alexa.reshape(6,3)
alexaN

array([[91,  4,  5],
       [58, 65,  2],
       [ 3,  5,  6],
       [ 1,  5,  7],
       [ 8,  9,  6],
       [ 4,  5,  8]])

In [25]:
#axis =0 means mean for colomn
np.mean(alexaN,axis=0)

array([27.5       , 15.5       ,  5.66666667])

In [26]:
np.var(alexaN,axis=0)

array([1199.58333333,  492.58333333,    3.55555556])

In [27]:
np.var(alexaN,axis=1)

array([1.66288889e+03, 7.94888889e+02, 1.55555556e+00, 6.22222222e+00,
       1.55555556e+00, 2.88888889e+00])

In [28]:
#axis =1 means mean for row
np.mean(alexaN,axis=1)

array([33.33333333, 41.66666667,  4.66666667,  4.33333333,  7.66666667,
        5.66666667])

In [29]:
#axis =0 means std for colomn
np.std(alexaN,axis=0)

array([34.63500156, 22.19421847,  1.88561808])

In [30]:
#axis =1 means std for row
np.std(alexaN,axis=1)

array([40.77853466, 28.19377394,  1.24721913,  2.49443826,  1.24721913,
        1.69967317])

In [31]:
alexaN.min()

1

In [32]:
alexaN.max()

91

In [33]:
rangevar=alexaN.max()-alexaN.min()
rangevar

90

### percentile

In [34]:
marks =np.array([91,4,5,58,65,2,3,5,6,1,5,7,8,9,6,4,5,8])
marks

array([91,  4,  5, 58, 65,  2,  3,  5,  6,  1,  5,  7,  8,  9,  6,  4,  5,
        8])

In [35]:
#percetile of mark variable where 60% of people fall below
np.percentile(marks,60)

6.199999999999999

In [36]:
np.percentile(marks,10)

2.7

In [37]:
np.percentile(marks,80)

8.600000000000001

# Live session 17.07.2021

pandas statistics

In [38]:
ph=pd.read_csv("president_heights.csv")
ph.head()

order               name  height
0     1  George Washington   189.0
1     2         John Adams   170.0
2     3   Thomas Jefferson   189.0
3     4      James Madison   163.0
4     5       James Monroe   183.0

In [39]:
ph['height'].isnull().sum()

1

In [40]:
import pandas as pd

In [41]:
ph["height"].describe()

count     42.000000
mean     179.738095
std        7.015869
min      163.000000
25%      174.250000
50%      182.000000
75%      183.000000
max      193.000000
Name: height, dtype: float64

In [42]:
height=ph["height"]

In [43]:
def Height_details ():
    print("Mean of height is ", height.mean())
    print("Median of height is ", height.median())
    print("Mode of height is ", height.mode())
    print("minimum of height is ", height.min())
    print("Max of height is ", height.max())

In [44]:
print("st_dev of height is ", height.std())
print("Variance of height is ", height.var())
print("25th percentile of height is ",np.percentile(height, 25))

st_dev of height is  7.015868855358296
Variance of height is  49.22241579558653
25th percentile of height is  nan


In [45]:
height.count()

42

In [46]:
q=np.percentile(height,60)
q

nan

In [47]:
np.nanpercentile(ph['height'], 60) # because null values you have in dataset 
# if u have any null values in dataset use nanpercentile
# let me know if have any more query
#no thanks . thats alll . thanks for the addition . 
# iam closing the anydesk 
#ok

183.0

In [48]:
Height_details()

Mean of height is  179.73809523809524
Median of height is  182.0
Mode of height is  0    183.0
dtype: float64
minimum of height is  163.0
Max of height is  193.0


In [49]:
# i am sorry i am taking too much time yours but please give  am moment 
#k go ahead 



In [50]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')




In [51]:
import numpy as np
import scipy as sp
from  scipy import stats 
from scipy.stats import percent
warnings.filterwarnings('ignore')

sp.__version__


'1.5.2'

In [60]:
a=np.array([[1,3,5],[1,3,5],[4,5,8],[5,6,7]]),
a

(array([[1, 3, 5],
        [1, 3, 5],
        [4, 5, 8],
        [5, 6, 7]]),)

In [53]:
sp.mean(a)

4.416666666666667

In [54]:
sp.median(a)

5.0

In [55]:
sp.stats.mode(a)

ModeResult(mode=array([[[1, 3, 5],
        [1, 3, 5],
        [4, 5, 8],
        [5, 6, 7]]]), count=array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]]))

In [56]:
b=np.array([1,5,8,8,6,4,6,7,6,6])

In [57]:
sp.stats.mode(b)

ModeResult(mode=array([6]), count=array([4]))

In [58]:
sp.var(b)

3.810000000000001

In [59]:
sp.std(a)

2.059867849051379

In [69]:
marks =pd.read_csv("Student_mark.csv")
m1=pd.DataFrame(marks)
m1.head(3)

Unnamed: 0 Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0       John      M  05-04-1988     55       45         56       87       21   
1     Suresh      M  04-05-1987     75       96         78       64       90   
2     Ramesh      M  25-05-1989     25       54         89       76       95   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74

In [72]:
m1["Maths"].mean()

59.6

In [73]:
m1["English"].mode()
#polymodal dataset 

0    46
1    56
2    58
3    63
4    64
5    75
6    76
7    83
8    87
9    89
dtype: int64

In [74]:
sp.median(m1["Physics"])

70.0

In [77]:
round (m1.describe () , 2)

Maths  Physics  Chemistry  English  Biology  Economics  History  Civics
count  10.00    10.00      10.00    10.00    10.00      10.00    10.00   10.00
mean   59.60    72.30      75.30    69.70    64.70      72.70    69.70   60.50
std    19.46    20.66      14.00    14.45    27.00      14.63    14.45   25.34
min    25.00    45.00      52.00    46.00    21.00      52.00    46.00    2.00
25%    54.25    56.25      65.00    59.25    54.25      58.75    59.25   52.25
50%    55.00    70.00      78.00    69.50    66.50      76.00    69.50   63.00
75%    70.75    93.75      86.75    81.25    87.00      86.00    81.25   76.25
max    96.00    96.00      89.00    89.00    96.00      89.00    89.00   89.00