# Min-Max scaling 

In [4]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler 
data=asarray([[1000,0.21],[8,0.555],[50,0.5557],[9999,15]])
data

array([[1.000e+03, 2.100e-01],
       [8.000e+00, 5.550e-01],
       [5.000e+01, 5.557e-01],
       [9.999e+03, 1.500e+01]])

In [5]:
scaler=MinMaxScaler()
scaled=scaler.fit_transform(data)
scaled

array([[0.09928936, 0.        ],
       [0.        , 0.02332657],
       [0.00420378, 0.0233739 ],
       [1.        , 1.        ]])

# Standard scaler

In [6]:
from sklearn.preprocessing import StandardScaler 
data1=asarray([[1000,0.21],[8,0.555],[50,0.5557],[9999,15]])
data1

array([[1.000e+03, 2.100e-01],
       [8.000e+00, 5.550e-01],
       [5.000e+01, 5.557e-01],
       [9.999e+03, 1.500e+01]])

In [9]:
scalee=StandardScaler()
newdata=scalee.fit_transform(data1)
newdata 

array([[-0.42048209, -0.61371535],
       [-0.65691016, -0.55900676],
       [-0.6469001 , -0.55889576],
       [ 1.72429235,  1.73161787]])